{
  "module_id": "acquisition",
  "model_pack_path": "model-packs/acquisition.model-pack.json",
  "source_event_dir": "source-events",
  "accepted_context_path": "ontology/accepted-context.json",
  "package_output_dir": "model-change-packages",
  "review_package_output_dir": "review-packages",
  "trace_path": "traces/events.jsonl",
  "digest_path": "digests/weekly-digest.md",
  "state_path": "agent-state/resident-loop-ledger.json",
  "store_path": "agent-state/operational-store.sqlite",
  "learnings_path": ".learnings/LEARNINGS.md",
  "authorization_checklist_path": ".operator/setup/AUTHORIZATION_CHECKLIST.md",
  "observer_protocol_path": ".operator/live-test/OBSERVER_PROTOCOL.md",
  "live_test_status_path": ".operator/live-test/STATUS.md",
  "artifact_root": ".",
  "state_root": "agent-state",
  "ontology_revision": "git:replace-with-accepted-revision",
  "generated_at": "2026-06-22T00:00:00Z",
  "digest_threshold": 1,
  "summary_package_limit": 20,
  "digest_package_limit": 20,
  "write_digest": true
}
