{
  "module_id": "acquisition",
  "company_model_language": "pending-owner-selection",
  "company_model_language_source": "pending-owner-onboarding",
  "model_pack_path": "model-packs/acquisition.model-pack.json",
  "raw_source_root": "raw",
  "source_event_dir": "source-events",
  "accepted_context_path": "model/ontology/accepted-context.json",
  "package_output_dir": "model-change-packages",
  "review_package_output_dir": "review-packages",
  "trace_path": "traces/events.jsonl",
  "digest_path": "digests/daily-digest.md",
  "state_path": "agent-state/resident-loop-ledger.json",
  "store_path": "agent-state/operational-store.sqlite",
  "source_instances_path": "source-instances.json",
  "live_proof_ledger_path": "live-proofs/proofs.json",
  "model_access_policy_path": "model-access-policy.json",
  "review_authority_policy_path": "agent-state/review-authority.json",
  "viewer_output_path": "viewer",
  "viewer_publish_report_path": "viewer/VIEWER_PUBLISH_REPORT.json",
  "viewer_publication": {
    "mode": "workspace-only",
    "public_url": ""
  },
  "learnings_path": ".learnings/LEARNINGS.md",
  "authorization_checklist_path": ".operator/setup/AUTHORIZATION_CHECKLIST.md",
  "observer_protocol_path": ".operator/live-test/OBSERVER_PROTOCOL.md",
  "live_test_status_path": ".operator/live-test/STATUS.md",
  "interaction_contract_path": "INTERACTION_CONTRACT.md",
  "artifact_root": ".",
  "state_root": "agent-state",
  "ontology_revision": "git:replace-with-accepted-revision",
  "generated_at": "2026-06-22T00:00:00Z",
  "digest_threshold": 1,
  "summary_package_limit": 20,
  "digest_package_limit": 20,
  "write_digest": true
}
